AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  peerOwnerId:
    Type: String
    Description: AWS account Id

  peerVpcId: 
    Type: String
    Description: Development account VPC
    
  peerRoleArn: 
    Type: String
    Description: AMS service role in the development account

Resources:

## VPC Peering Connections
  devToProPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      PeerOwnerId: !Ref peerOwnerId
      PeerRegion: !Ref AWS::Region
      PeerVpcId: !Ref peerVpcId
      PeerRoleArn: !Ref peerRoleArn
      VpcId: !Ref mainVpc
